// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package configuration

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "shopTemplate/app/config"

func FacebookPixel(cfg *config.Config) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"space-y-6\" id=\"facebook-pixel-settings\"><form hx-post=\"/admin/facebook_pixel\" hx-target=\"#facebook-pixel-settings\" hx-swap=\"outerHTML\"><div class=\"bg-white shadow px-4 py-5 sm:rounded-lg sm:p-6\"><div class=\"md:grid md:grid-cols-3 md:gap-6\"><div class=\"md:col-span-1\"><h3 class=\"text-lg font-medium leading-6 text-gray-900\">Facebook Pixel</h3><p class=\"mt-1 text-sm text-gray-500\">Configure your Facebook Pixel for tracking conversions and user activity.</p></div><div class=\"mt-5 md:mt-0 md:col-span-2\"><div class=\"grid grid-cols-6 gap-6\"><div class=\"col-span-6\"><label for=\"pixel_id\" class=\"block text-sm font-medium text-gray-700\">Facebook Pixel ID</label> <input type=\"text\" name=\"pixel_id\" id=\"pixel_id\" value=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.ResolveAttributeValue(cfg.FacebookPixel.PixelID)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `app/views/configuration/facebook_pixel.templ`, Line: 18, Col: 90}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var2)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "\" class=\"mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm\" placeholder=\"e.g. 123456789012345\"></div><div class=\"col-span-6\"><label for=\"access_token\" class=\"block text-sm font-medium text-gray-700\">Conversion API Access Token (CAPI)</label> <input type=\"password\" name=\"access_token\" id=\"access_token\" value=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var3 string
		templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.ResolveAttributeValue(cfg.FacebookPixel.AccessToken)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `app/views/configuration/facebook_pixel.templ`, Line: 23, Col: 106}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var3)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "\" class=\"mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm\" placeholder=\"e.g. EAAB...\"><p class=\"mt-1 text-xs text-gray-500 italic\">This token allows your server to send events directly to Facebook, bypassing browser-side blockers.</p></div><div class=\"col-span-6\"><label for=\"domain_verification\" class=\"block text-sm font-medium text-gray-700\">Domain Verification Meta Tag</label> <input type=\"text\" name=\"domain_verification\" id=\"domain_verification\" value=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var4 string
		templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.ResolveAttributeValue(cfg.FacebookPixel.DomainVerification)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `app/views/configuration/facebook_pixel.templ`, Line: 29, Col: 123}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var4)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "\" class=\"mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm\" placeholder=\"e.g. random-string-of-characters\"><p class=\"mt-1 text-xs text-gray-500 italic\">Enter only the verification code (the value inside content=\"...\").</p></div><div class=\"col-span-6\"><label for=\"test_event_code\" class=\"block text-sm font-medium text-gray-700\">Test Event Code (Optional)</label> <input type=\"text\" name=\"test_event_code\" id=\"test_event_code\" value=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var5 string
		templ_7745c5c3_Var5, templ_7745c5c3_Err = templ.ResolveAttributeValue(cfg.FacebookPixel.TestEventCode)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `app/views/configuration/facebook_pixel.templ`, Line: 35, Col: 110}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var5)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "\" class=\"mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm\" placeholder=\"e.g. TEST12345\"><p class=\"mt-1 text-xs text-gray-500 italic\">Use this to see your server events in the Facebook \"Test Events\" tab in real-time. Remove this when you are done testing.</p></div><div class=\"col-span-6\"><div class=\"flex items-start\"><div class=\"flex items-center h-5\"><input id=\"track_purchase_value\" name=\"track_purchase_value\" type=\"checkbox\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if cfg.FacebookPixel.TrackPurchaseValue {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, " checked")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, " class=\"focus:ring-indigo-500 h-4 w-4 text-indigo-600 border-gray-300 rounded\"></div><div class=\"ml-3 text-sm\"><label for=\"track_purchase_value\" class=\"font-medium text-gray-700\">Track Purchase Value</label><p class=\"text-gray-500\">Enable this to send the order total to Facebook.</p></div></div></div></div></div></div></div><div class=\"mt-6 flex items-center justify-end\"><button type=\"submit\" class=\"inline-flex justify-center rounded-md border border-transparent bg-indigo-600 py-2 px-4 text-sm font-medium text-white shadow-sm hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2\">Save Settings</button></div></form></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
