// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package configuration

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "shopTemplate/app/config"

func Notifications(cfg *config.Config) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"space-y-6\" id=\"notifications-settings\"><form hx-post=\"/admin/notifications\" hx-target=\"#notifications-settings\" hx-swap=\"outerHTML\"><div class=\"bg-white shadow px-4 py-5 sm:rounded-lg sm:p-6\"><div class=\"md:grid md:grid-cols-3 md:gap-6\"><div class=\"md:col-span-1\"><h3 class=\"text-lg font-medium leading-6 text-gray-900\">Email Notifications</h3><p class=\"mt-1 text-sm text-gray-500\">Configure email settings for order notifications.</p></div><div class=\"mt-5 md:mt-0 md:col-span-2\"><div class=\"grid grid-cols-6 gap-6\"><div class=\"col-span-6 sm:col-span-4\"><label for=\"admin_email_recipient\" class=\"block text-sm font-medium text-gray-700\">Admin Notification Email</label> <input type=\"email\" name=\"admin_email_recipient\" id=\"admin_email_recipient\" value=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.ResolveAttributeValue(cfg.Notification.AdminEmailRecipient)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `app/views/configuration/notifications.templ`, Line: 18, Col: 128}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var2)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "\" class=\"mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm\"><p class=\"mt-2 text-sm text-gray-500\">This email address will receive a copy of all new order notifications.</p></div></div><div class=\"mt-6\"><button type=\"button\" hx-post=\"/admin/notifications/test\" hx-include=\"#admin_email_recipient\" hx-swap=\"none\" class=\"inline-flex justify-center rounded-md border border-gray-300 bg-white py-2 px-4 text-sm font-medium text-gray-700 shadow-sm hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2\">Send Test Email</button></div></div></div></div><div class=\"bg-white shadow px-4 py-5 sm:rounded-lg sm:p-6 mt-6\"><div class=\"md:grid md:grid-cols-3 md:gap-6\"><div class=\"md:col-span-1\"><h3 class=\"text-lg font-medium leading-6 text-gray-900\">Telegram Notifications</h3><p class=\"mt-1 text-sm text-gray-500\">Receive instant order alerts via a Telegram bot.</p></div><div class=\"mt-5 md:mt-0 md:col-span-2\"><div class=\"grid grid-cols-6 gap-6\"><div class=\"col-span-6 sm:col-span-4\"><label for=\"telegram_bot_token\" class=\"block text-sm font-medium text-gray-700\">Bot Token</label> <input type=\"text\" name=\"telegram_bot_token\" id=\"telegram_bot_token\" value=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var3 string
		templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.ResolveAttributeValue(cfg.Notification.TelegramBotToken)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `app/views/configuration/notifications.templ`, Line: 47, Col: 118}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var3)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "\" class=\"mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm\"></div><div class=\"col-span-6 sm:col-span-4\"><label for=\"telegram_chat_id\" class=\"block text-sm font-medium text-gray-700\">Chat ID</label> <input type=\"text\" name=\"telegram_chat_id\" id=\"telegram_chat_id\" value=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var4 string
		templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.ResolveAttributeValue(cfg.Notification.TelegramChatID)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `app/views/configuration/notifications.templ`, Line: 51, Col: 112}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var4)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "\" class=\"mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm\"><p class=\"mt-2 text-sm text-gray-500\">Find your Chat ID using bots like @userinfobot.</p></div></div><div class=\"mt-6\"><button type=\"button\" hx-post=\"/admin/notifications/test/telegram\" hx-include=\"#telegram_bot_token, #telegram_chat_id\" hx-swap=\"none\" class=\"inline-flex justify-center rounded-md border border-gray-300 bg-white py-2 px-4 text-sm font-medium text-gray-700 shadow-sm hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2\">Send Test Telegram</button></div></div></div></div><div class=\"mt-6 flex items-center justify-end gap-4\"><button type=\"submit\" class=\"inline-flex justify-center rounded-md border border-transparent bg-indigo-600 py-2 px-4 text-sm font-medium text-white shadow-sm hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2\">Save Settings</button></div></form></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
