// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package products

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"fmt"
	"shopTemplate/app/config"
	"shopTemplate/app/models"
)

func EditModal(product models.Product, allCategories []models.Category, cfg *config.Config) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div id=\"modal\" class=\"fixed inset-0 bg-gray-500 bg-opacity-75 flex items-center justify-center z-50\" hx-target=\"this\"><div class=\"bg-white rounded-lg shadow-xl p-6 w-full max-w-lg\" role=\"dialog\" aria-modal=\"true\"><div class=\"flex justify-between items-center mb-4 border-b border-gray-100 pb-4\"><h2 class=\"text-xl font-bold\">Edit Product</h2><a href=\"/admin/products\" class=\"text-gray-400 hover:text-gray-600\">&times;</a></div><form hx-put=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.ResolveAttributeValue(fmt.Sprintf("/products/%d", product.ID))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `app/views/products/edit_modal.templ`, Line: 17, Col: 52}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var2)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "\" hx-encoding=\"multipart/form-data\" hx-target=\"body\"><div class=\"max-h-[70vh] overflow-y-auto pr-2 custom-scrollbar\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = ProductFormFields(FormParams{
			Product:       product,
			AllCategories: allCategories,
			Values: map[string]string{
				"name":        product.Name,
				"description": product.Description,
				"price":       fmt.Sprintf("%.3f", product.Price.ToFloat()),
				"promotion_price": func() string {
					if product.PromotionPrice > 0 {
						return fmt.Sprintf("%.3f", product.PromotionPrice.ToFloat())
					}
					return ""
				}(),
				"stock": fmt.Sprint(product.Stock),
			},
			SelectedCatIDs: getSelectedCategoryIDs(product.Categories),
			IsEdit:         true,
		}, cfg).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</div><div class=\"mt-6 flex justify-end gap-3 pt-4 border-t border-gray-100\"><a href=\"/admin/products\" class=\"px-4 py-2 bg-gray-200 text-gray-800 rounded-md hover:bg-gray-300\">Cancel</a> <button type=\"submit\" class=\"px-4 py-2 bg-primary text-primary-foreground rounded-md hover:bg-primary/90 shadow-sm\">Save Changes</button></div></form></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func getSelectedCategoryIDs(cats []models.Category) map[uint]bool {
	ids := make(map[uint]bool)
	for _, cat := range cats {
		ids[cat.ID] = true
	}
	return ids
}

var _ = templruntime.GeneratedTemplate
